import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";

import { loadThemeLibraries } from "../src/theme/theme-library.js";

const outputDirectory = path.resolve("references/themes");

await rm(outputDirectory, { recursive: true, force: true });
await mkdir(outputDirectory, { recursive: true });
const libraries = await loadThemeLibraries(process.cwd());
for (const library of libraries) {
  const output = path.join(outputDirectory, `${library.manifest.id}.md`);
  await writeFile(output, guideFor(library), "utf8");
  process.stdout.write(`${output}\n`);
}

function guideFor(library: Awaited<ReturnType<typeof loadThemeLibraries>>[number]): string {
  const { manifest, components } = library;
  const tokenSummary = JSON.stringify(manifest.tokens, null, 2);
  const componentSource = components.map((component) => [
    `### ${component.id} · ${component.kind}`,
    "",
    `- 默认变体：\`${component.fallbackVariant}\``,
    `- 可接受：\`${component.accepts.blockTypes.join(", ")}\`${component.accepts.levels ? `；层级 ${component.accepts.levels.join(", ")}` : ""}`,
    `- Slot：${component.slots.map((slot) => `\`${slot.name}:${slot.source}\``).join("，")}`,
    "",
    "组件定义：",
    "```json",
    JSON.stringify(((component) => {
      const { templateHtml, ...definition } = component;
      return definition;
    })(component), null, 2),
    "```",
    "",
    "模板：",
    "```html",
    component.templateHtml.trim(),
    "```",
  ].join("\n")).join("\n\n");
  const recipeRows = manifest.composition.recipes.map((recipe) =>
    `| \`${recipe.id}\` | ${recipe.label} | ${recipe.articleTypes.join("、")} | ${recipe.coreComponents.map((id) => `\`${id}\``).join("、")} | ${recipe.accentComponents.map((id) => `\`${id}\``).join("、") || "无"}（≤ ${recipe.maxAccentKinds} 类） | ${recipe.guidance.join("；")} |`,
  ).join("\n");
  const mappingRows = manifest.composition.mappings.map((mapping) =>
    `| ${mapping.blockTypes.map(markdownConvention).join("、")} | ${mapping.blockTypes.map((type) => `\`${type}\``).join("、")} | ${mapping.levels?.join("、") ?? "—"} | \`${mapping.componentId}\` |`,
  ).join("\n");
  const skeleton = manifest.composition.mappings.map((mapping) =>
    `- ${mapping.blockTypes.join(" / ")}${mapping.levels ? `（H${mapping.levels.join("/H")}）` : ""} → \`${mapping.componentId}\``,
  ).join("\n");
  const chrome = manifest.composition.chrome;
  const chromeRows = [
    ["引言", chrome.intro.enabled ? "首段首句摘引；原文仍在正文原位" : "关闭"],
    ["目录", chrome.directory.enabled ? `最多 ${chrome.directory.maxItems} 个非结语标题` : "关闭"],
    ["英文标签", chrome.chapter.enabled ? `标题前的序号 · ${chrome.chapter.label}` : "关闭"],
    ["END", chrome.end.enabled ? chrome.end.label : "关闭"],
    ["作者 / CTA", chrome.signature.enabled ? `${chrome.signature.authorTemplate} / ${chrome.signature.ctaTemplate}` : "关闭"],
  ].map(([element, rule]) => `| ${element} | ${rule} |`).join("\n");
  const inlineBudget = manifest.composition.inlineMarkBudget;
  return `<!-- Generated by npm run docs:themes. Edit .themes/${manifest.id}/ instead. -->
# 公众号排版组件库 —— ${manifest.name}

> ${manifest.description}

## 设计变量速查表

结构模型：${manifest.composition.structureModel}

\`\`\`json
${tokenSummary}
\`\`\`

## 各组件完整实现

${componentSource}

## 完整文章模板骨架

该骨架由渲染器按语义块自动装配；它不含文章正文，正文只能从原文 Slot 绑定。

${skeleton}

## 派生版式层

这几项只由原文结构派生，不进入 source span，也不参与原文完整性比对：引言只摘取首段首句；目录只读取已识别标题；章节标签、END、作者占位和 CTA 是主题声明的版式外壳，绝不替换或改写正文。

| 元素 | 当前主题规则 |
| --- | --- |
${chromeRows}

## 正文行内标记预算

自动标记只在有明确语义依据时增加，绝不改写原文；作者在 Markdown 中写下的行内标记原样保留。概念词使用主题的 \`strong\`（加粗 + 主题色）样式，数据/时长使用 \`highlight\`（浅底高亮）。

| 约束 | 当前主题规则 |
| --- | --- |
| 单段自动标记 | ${inlineBudget.minPerParagraph}–${inlineBudget.maxPerParagraph} 个；没有明确重点可为 0 |
| 短语长度 | 通常 ${inlineBudget.preferredPhraseMinChars}–${inlineBudget.preferredPhraseMaxChars} 字；关键数据、专名可更短 |
| 浅底高亮 | 单段最多 ${inlineBudget.maxHighlightPerParagraph} 个 |
| 强调样式种类 | 单段最多 ${inlineBudget.maxStyleKindsPerParagraph} 种 |
| 强锚点 | 全文最多 ${inlineBudget.maxStrongAnchorsPerArticle} 个，另由强组件预算约束 |

## 文章类型 → 组件组合配方

| 配方 | 名称 | 文章类型 | 核心组件 | 点缀组件 | 使用原则 |
| --- | --- | --- | --- | --- | --- |
${recipeRows}

## Markdown / 语义块 → 组件映射规则

Markdown 会先保真解析为 BlockDocument，再按这张表选择默认组件；少量特殊重点由 Agent 的内部渲染计划显式声明，不能随机套卡片。

| Markdown / 输入结构 | 语义块 | 标题层级 | 默认组件 |
| --- | --- | --- | --- |
${mappingRows}
`;
}

function markdownConvention(blockType: string): string {
  const conventions: Record<string, string> = {
    "article-title": "首个标题或首段",
    "article-subtitle": "`*图注：…*`",
    lead: "标题后的首段",
    heading: "`一、标题` / `01 | 标题`",
    paragraph: "普通段落",
    list: "连续 `-` 或 `1.` 列表",
    quote: "独立 `**重点句**`",
    callout: "原则 / 提示语义块",
    image: "图片语义块",
    ending: "结语章节内容",
    cta: "行动标题及其后内容",
  };
  return conventions[blockType] ?? `\`${blockType}\``;
}
